### ISSUE TITLE
grammar.y seems to be missing a few from my list

### ISSUE THREAD

**Issue by DavidPhillipOster** [lduck11007/x#1]
grammar.y seems to be missing a few from this list
🅇𝗑𝖷𝐱𝐗x⃞X⃞x⃫X⃫ⓧⓍ𝕩𝕏𝘅𝗫𝑥𝑋ᵡx⃟X⃟x̶X̶𝚡𝚇𝒙𝑿x⃒X⃒x̷X⃫🆇𝔵𝔛𝘹𝘟𝓍𝒳x⃦X⃦x̷X̶🅧𝖝𝖃𝙭𝙓𝔁𝓧x⃣X⃣x̷X̷

and that's just Unicode, not even trying other fonts. I haven't looked at Chinese, Japanese, or Korean  (looks best when viewed from Safari on Mac)

**Comment by fezboy** [comment]
While these should be added, font parsing would require the use of a richtext format and a full rehash of the parsing system, imo far more work than it's worth

**Comment by leowhitehead** [comment]
Thanks for bringing these up. I'll certainly expand the list of allowed identifiers at some point.

**Comment by DavidPhillipOster** [comment]
྾ྈ - Tibetan
ᚷ - Runic
ᯬ - Batak
᥊ - Limbu
᰽ - lepcha
ᳵ - vedic
ᵡ  ᵪ - phonetic extension
Ẋ ẋ Ẍ ẍ - Latin Extended
Ⅹⅹ - number forms
╳ - box drawing
⚔ 
✕✖✗✘ - dingbats (I think you already have these)
⤫⤬
⪥ - supplemental math
Ⲭⲭ - Coptic
ⷯⷯⷯ  - combining cyrillic
㐅 - CJK
ꓫ Lisu
ꭓ - Latin Extended E
Ｘｘ- fullwidth
𐊉 -  Lycian
𐊴 - Carian
𐩩 - old south arabian
𐰓 - old turkic
𑀋 𑀌 - Brahmi
𓌖 𓏴 - Egyptian Hieroglyph
🄧 🇽
Thank you very much for taking these under consideration. Thank you for creating this language.

**Comment by leowhitehead** [comment]
Thanks @DavidPhillipOster, I've just added a set of new identifiers in commit 451b09e. I need no praise or thanks for my work, I am simply doing what must be done.
