### ISSUE TITLE
README.MD uses more than Ten Hundred Most Common Words

### ISSUE THREAD

**Issue by deefdragon** [lduck11007/x#3]
Readme uses more than Ten Hundred Most Common Words

X: A programming language that only accepts identifiers that look like the letter 'x'. 
X: An Electric-Box language that only uses name-words that look like the letter 'x'.

**Comment by leowhitehead** [comment]
Thanks for bringing this up. If we're going to fix README.md, there's also quite a few other words we need to deal with. I haven't checked yet, but I'm willing to bet that 'transcompiled', 'unicode' and 'stdout' are also not in the ten hundred most common words either. If we're going to go down that rabbit-hole also, the entire src/ directory contains words that aren't very common.
