### ISSUE TITLE
>< should be added to x-like characters

### ISSUE THREAD

**Issue by aidangilmore** [lduck11007/x#4]

**Comment by RKDUDE02** [comment]
Thats a good idea

**Comment by vmkalbskopf** [comment]
I support this, even though it will greatly complicate parsing.

**Comment by RKDUDE02** [comment]
> I support this, even though it will greatly complicate parsing.

Good point

**Comment by ghost** [comment]
_"Except the only variable name is 'X'. To refer to different variables you have to write 'X' in different fonts."_ I'd prefer if the language stayed true to the source material. _><_ isn't the letter _x_, therefore it can't be used as an identifier.

**Comment by leowhitehead** [comment]
I think I agree with @AviPerl on this one. I probably won't be adding support for '><' at this moment.
